# Generated by Django 4.2.6 on 2023-10-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_remove_contact_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact',
            field=models.BooleanField(default=True),
        ),
    ]
