# Generated by Django 4.2.6 on 2023-10-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_customuser_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, default='#00000', max_length=100)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
