# Generated by Django 4.2.6 on 2023-10-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_remove_task_assignee'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserAndContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('color', models.CharField(blank=True, default='#00000', max_length=100)),
                ('initials', models.CharField(blank=True, default='', max_length=100)),
                ('user_name', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=100)),
                ('contact', models.BooleanField(default=False)),
            ],
        ),
    ]
