# Generated by Django 4.2.6 on 2023-10-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_customuserandcontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUserAndContact',
        ),
        migrations.RemoveField(
            model_name='task',
            name='subtask_done',
        ),
        migrations.RemoveField(
            model_name='task',
            name='subtask_title',
        ),
    ]
