# Generated by Django 4.2.6 on 2023-10-31 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_delete_subtask_task_subtasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='prio',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
