# Generated by Django 4.2.6 on 2023-10-31 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0015_rename_contact_customuser_user_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact',
            new_name='user_contact',
        ),
    ]
