# Generated by Django 4.2.6 on 2023-11-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0019_remove_category_created_by_remove_task_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='task',
            name='custom_users',
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_emails',
            field=models.JSONField(default=dict),
        ),
    ]
