# Generated by Django 4.2.6 on 2023-11-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0020_remove_task_contacts_remove_task_custom_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='creator_email',
            field=models.EmailField(blank=True, default='', max_length=70),
        ),
    ]
