# Generated by Django 4.2.6 on 2023-11-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0021_category_creator_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
